name: Next.js CI

on:
  push:
    branches: [feature/instagram-stories]
  pull_request:
    branches: [feature/instagram-stories]
env:
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: "daprs0abn"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.18.2]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - name: Test Application
        run: yarn test
      - name: Build Application
        run: yarn build
